Block 2048
( first init.4th )
: STAR 42 EMIT ;
: STARS 0 DO STAR LOOP ;
: MARGIN 30 SPACES ;
: BAR MARGIN 5 STARS CR ;
: BLIP MARGIN STAR CR ;
: BLIPBLIP MARGIN STAR 3 SPACES STAR CR ;


: F CR BAR BLIP BAR BLIP BLIP CR ;
: H CR BLIPBLIP BLIPBLIP BAR BLIPBLIP BLIPBLIP CR ;

F H

S" ACL.4th" EXEC
ACL-BOOT
